packages:
  - addons/*

overrides:
  serialize-javascript: ^7.1.1

allowBuilds:
  esbuild: true
  node-pty: true

minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@1.82.0'
  - '@oxlint/binding-android-arm64@1.82.0'
  - '@oxlint/binding-darwin-arm64@1.82.0'
  - '@oxlint/binding-darwin-x64@1.82.0'
  - '@oxlint/binding-freebsd-x64@1.82.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.82.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.82.0'
  - '@oxlint/binding-linux-arm64-gnu@1.82.0'
  - '@oxlint/binding-linux-arm64-musl@1.82.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.82.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.82.0'
  - '@oxlint/binding-linux-riscv64-musl@1.82.0'
  - '@oxlint/binding-linux-s390x-gnu@1.82.0'
  - '@oxlint/binding-linux-x64-gnu@1.82.0'
  - '@oxlint/binding-linux-x64-musl@1.82.0'
  - '@oxlint/binding-openharmony-arm64@1.82.0'
  - '@oxlint/binding-win32-arm64-msvc@1.82.0'
  - '@oxlint/binding-win32-ia32-msvc@1.82.0'
  - '@oxlint/binding-win32-x64-msvc@1.82.0'
  - '@types/node@26.5.0'
  - '@typescript-eslint/eslint-plugin@8.70.0'
  - '@typescript-eslint/parser@8.70.0'
  - '@typescript-eslint/project-service@8.70.0'
  - '@typescript-eslint/scope-manager@8.70.0'
  - '@typescript-eslint/tsconfig-utils@8.70.0'
  - '@typescript-eslint/type-utils@8.70.0'
  - '@typescript-eslint/types@8.70.0'
  - '@typescript-eslint/typescript-estree@8.70.0'
  - '@typescript-eslint/utils@8.70.0'
  - '@typescript-eslint/visitor-keys@8.70.0'
  - eslint-plugin-oxlint@1.82.0
  - oxlint-plugin-eslint@1.82.0
  - oxlint@1.82.0
  - typescript-eslint@8.70.0
